def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()
    }
}
pipeline {
    agent any

    stages {
        stage('Build image based on ci.Dockerfile') {
            steps {
                script { 
                    docker.build('python-app:latest', '-f devops/ci.Dockerfile .')                    
                }
            }
        }

        stage('Test') {
            steps {
                runInDocker('python-app:latest') {
                    sh 'pytest -q'
                }
            }
        }

        stage('Lint') {
            steps {
                runInDocker('python-app:latest') {
                    sh 'make lint'
                }
            }
        }
        stage('Build image') {
            steps {
                script { 
                   
                    def image = docker.build('python-app:${BUILD_NUMBER}', '-f devops/Dockerfile .')
                    echo "Image tag: python-app:${BUILD_NUMBER}"
                    echo "Image ID: ${image.id}"
                }
            }
        }
    }
}
