def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()
    }
}
pipeline {
    agent any

    stages {
        stage('Build image based on ci.Dockerfile') {
            steps {
                script { 
                    docker.build('python-app:latest', '-f devops/ci.Dockerfile .')                    
                }
            }
        }

        stage('Test') {
            steps {
                runInDocker('python-app:latest') {
                    sh 'pytest -q'
                }
            }
        }

        stage('Lint') {
            steps {
                runInDocker('python-app:latest') {
                    sh 'make lint'
                }
            }
        }
        stage('Build image') {
            steps {
                  script {
                    def tag = env.BUILD_NUMBER ?: 'latest'
                    def imageName = "python-app:${tag}"
                    echo "Building Docker image: ${imageName}"
                    def image = docker.build(imageName, '-f devops/Dockerfile .')
                    echo "Built image tag: ${imageName}"
                    echo "Image ID: ${image.id}"
    }
            }
        }
    }
}
