def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()
    }
}
pipeline {
    agent any
    parameters {
        booleanParam(name: 'RUN_CD', defaultValue: false, description: 'Marcar para forzar el despliegue (CD)')
    }
    stages {
        stage('Build image based on ci.Dockerfile') {
            steps {
                script {
                    docker.build('python-app:latest', '-f devops/ci.Dockerfile .')
                }
            }
        }

        stage('Test') {
            steps {
                runInDocker('python-app:latest') {
                    sh 'pytest -q'
                }
            }
        }

        stage('Lint') {
            steps {
                runInDocker('python-app:latest') {
                    sh 'make lint'
                }
            }
        }
        stage('Build image') {
            steps {
                script {
                    def tag = env.BUILD_NUMBER ?: 'latest'
                    def imageName = "python-app:${tag}"
                    echo "Building Docker image: ${imageName}"
                    def image = docker.build(imageName, '-f devops/Dockerfile .')
                    echo "Built image tag: ${imageName}"
                    echo "Image ID: ${image.id}"
                }
            }
        }

        stage('CD') {
            when { //directiva when en Jenkins sirve para establecer condiciones, permitiendo ejecutar etapas solo si se cumplen ciertos criterios.

//el step se ejecutara si return params.RUN_CD == true  or branch 'develop'  or  branch 'master'
//if (RUN_CD == true  or branch 'develop'  or  branch 'master') then execute the steps

                anyOf { // operador lógico OR. Se cumple si al menos una de las condiciones es verdadera.
                    expression { return params.RUN_CD == true } //condición personalizada basada en un parámetro booleano RUN_CD definido en Jenkins. Si es true, se cumple esta condición.
                    branch 'develop'
                    branch 'master'
                }
            }

            steps {
                script {
                    echo "CD habilitado: RUN_CD=${params.RUN_CD}, branch=${env.BRANCH_NAME}"

                    echo 'Ejecutando aplicación con docker-compose'
                    sh 'docker compose up -d'
                    echo 'Esperando a que la aplicación se inicie...'
                    sh 'sleep 5'
                    echo 'Mostrando logs de la aplicación:'
                    sh 'docker compose logs app'
                }
            }
        }
    }
    post {
        always {
            script {
                echo 'Deteniendo y eliminando contenedores, redes y volúmenes de docker-compose'
                    sh 'docker compose down --volumes'
            }
        }
    }
}
